### ISSUE TITLE
meta-issue: stabilize OpenTracing 1.0RC semantics

### ISSUE THREAD

**Issue by bensigelman** [opentracing/opentracing.github.io#44]
I mentioned this in my [OpenTracing status report](https://docs.google.com/presentation/d/1Eexa7lZRCn7KE0w_4I0lZW99l2d-p7YbVyKylxWGz0Y/edit#slide=id.g108c88bc6a_0_18), but to reiterate here...

This is the rough sequence of steps before I would feel ok declaring an OpenTracing 1.0 semantic spec:

1. Agree that there’s a problem to solve
1. Agree on the basic approach / vision
1. Propose initial semantic spec and specific platform sketches, with examples
1. Converge on a “1.0RC” semantic specification (with rough implementations on multiple platforms)
1. Allow early-adopters to bind to the “1.0RC” spec (app programmers, IPC frameworks, control flow systems, and of course tracing implementations)
1. Converge on a “1.0” semantic spec and announce more broadly, "co-branded" with various OpenTracing users and implementations

Right now we are somewhere between (3) and (4) above, and this particular Issue is about getting to (4).

Here are the more controversial issues I'm remembering, some of which I think are mostly resolved:
- [x] Should DCP be modeled separately from Spans/etc? (Current answer: “no”)
- [x] Should we support a robust message logging API? (Current answer: “maybe, but not yet”)
- [x] Should we support (auto-propagated) “Trace Attributes”? (Current answer: “yes, with copious warnings in comments”)
- [x] How should the Propagator interface interoperate with IPC frameworks? (Undecided)
- [x] The best API for child-Span creation (Undecided)

There are also some lingering naming concerns, but I'm confident we can get through those if we deal with the semantics.

I would further suggest that we try to hash out the remaining sticking points via a google hangout rather than on Github. On that note, please fill out:

   http://doodle.com/poll/q82qiz932q9gm3dr

**If** we need to use Github due to timezone sadness, I would ask that we restrict ourselves to issues in [opentracing.github.io](https://github.com/opentracing/opentracing.github.io/issues) (creating new ones as needed) rather than fragmenting the discussions across per-language repos. And concerns about the current semantic spec should be accompanied by *specific* suggestions to the relevant [use cases](http://opentracing.io/use-cases/).

In alphabetical order: I suspect that some of @adriancole @bcronin @dkuebric @michaelsembwever @slimsag @yurishkuro might care about this... of course all are welcome to chime in!

(^^^ alphabetical order on the github usernames, btw :)

**Comment by bensigelman** [comment]
I was joined by @michaelsembwever @dkuebric @yurishkuro @bg451 for a hangout today, and we actually resolved a bunch of stuff. Thank you again to all of the above, much obliged!

**Should we consolidate the span-creation methods?**: basically, "Yes." There was agreement that we should do our best (within the confines of the platform) to consolidate around a `Tracer` method that creates a `Span`, regardless of whether that span will ultimately be a root or whether its parent is local or remote, etc. I don't think we came to a consensus about whether there should also be a way to create a child `Span` given a parent `Span` instance alone (i.e., without a `Tracer`)... But that decision can come later and would be built upon the singular mechanism mentioned above.

**Should we support Trace Attributes?** Yes, but with caveats in the comments, both about the possible dangers of the feature and also about the fact that the API may go away or change in incompatible ways if its "considered harmful" in the future.

**Should we go back to separated Span and TraceContext concepts/types?** No... it's conceptually tempting for sure, but it "makes the simple things complex" and we don't have enough adoption to get the "Span-free" version of DCP correct anyway.

**Can we do something like https://github.com/opentracing/opentracing.github.io/pull/45?** Yes. Though the details will be platform-dependent, there was support for the general idea of adding one more layer of indirection to get to a particular Injector/Extractor (or whatever we end up calling them).

Next steps:
- [ ] get Python to parity with Go
- [ ] experiment with injector/extractor registration patterns

**Comment by bensigelman** [comment]
(all should feel more than welcome to add to or correct anything about the above)

**Comment by yurishkuro** [comment]
> Should we consolidate the span-creation methods?

Not sure of practical implications of this one. I think we agreed to keep `span.start_child`, as well as move injector to the span level, so that the only place in the application that needs a Tracer reference is the server endpoint dealing with inbound requests. In addition, we still need two other span creation methods
 * `tracer.getExtractor(typeOf[x]).extract(x)` -> Span
 * `tracer.start_trace()` for standalone apps/clients

**Comment by bensigelman** [comment]
@yurishkuro `tracer.start_trace()` could be a special case of `tracer.create_span()` where there's no parentage info (at least conceptually; in Go there might be separate method variants).

**Comment by yurishkuro** [comment]
@bensigelman but when would we use `tracer.create_span()` except to start a new trace? The "parentage info" can only be another span, in which case we can do `span.start_chid()`.

**Comment by bensigelman** [comment]
I would probably break it down into three cases:

1. you have the propagated form of a Span (presumably from a different process) and want to resume tracing
1. you have a `Span` instance and you want to create a span to model some activity that's about to happen
1. you don't have a `Span` instance and you want to create a span to model some activity that's about to happen

Case (1) seems like a good reason to have `tracer.create_span()` independent of anything else. Case (2) is of course why I've been arguing for `span.start_child()` as a convenience method/synonym.

Case (3) is interesting and tricky... certainly it would be nice for the user if, once the in-process propagation story is clearer, cases (2) and (3) were covered by the same function call that did the equivalent of `get_current_span()` (from the use-cases doc) internally. In the meantime I do see an argument for separating the methods (esp in Go where it's almost required since the param counts are different), but the spirit of both is the same in my eyes: "create a span to model some activity that's about to happen".

Maybe the above is a long way of saying that I'm leaning towards a common method prefix of `Tracer.CreateSpan*` in Go (for both 2 and 3 above) and overloading `Tracer.create_span(op_name, parent_info=None)` in Python/etc.

**Comment by yurishkuro** [comment]
Isn't case (1) solved by the Extractor pattern?  I guess I am not seeing where `Tracer.create_span(op_name, parent_info=None)` would be used with `parent_info` not being None. Since we don't have a class to model "trace context" anymore, `parent_info` can only be another Span, thus this child can be started from there.

Case (3) is indeed interesting because it can occur not only at the edge, but sometimes deep inside the app, as here: https://github.com/uber-common/opentracing-python-instrumentation/blob/master/opentracing_instrumentation/local_span.py#L125.

**Comment by bensigelman** [comment]
I skipped a step in my reasoning, apologies... I am arguing that methods which return a newly-started Span should be in the same naming constellation, whether that implies overloading or a common prefix for a particular platform. This means that the Extractor interface would feature a method matching `CreateSpan*`, too.

**Comment by bensigelman** [comment]
re getting python to parity with Go: https://github.com/opentracing/opentracing-python/pull/14

**Comment by bensigelman** [comment]
We are in a good place after the recent merges in `opentracing-go`... I will make parallel changes to the `spec.md` and python, at which point we can close this issue.

- [ ] update docs site per opentracing/opentracing-go#48 and opentracing/opentracing-go#50
- [ ] update the python API to follow suit with the above

**Comment by bensigelman** [comment]
(yay)
